pgrid: t_grid Class Reference
t_grid Class Reference
#include <grid.h>
Public Member Functions
t_grid (int w, int h)
~t_grid ()
int wrap (int val, int c)
int clamp (int val, int c)
t_gridpoint & getpoint (int x, int y)
t_gridpoint & getpoint_editing (int x, int y)
void paint_pixel_additive (vec img_pos, float d)
void paint_pixels_additive (int px, int py, float *pixels, int w, int h, float amount, int stride=0)
void paint_pixels_additive (vec pos, float *pixels, int w, int h, float amount, int stride=0)
void render_quadstrips (float img_x, float img_y, float img_w, float img_h)
void render_quads (float img_x, float img_y, float img_w, float img_h)
void render_scanlines (float img_x, float img_y, float img_w, float img_h)
void render_arrays (float img_x, float img_y, float img_w, float img_h)
void render (float img_x, float img_y, float img_w, float img_h)
void fade (float time)
void phys_tick (float time)
Public Attributes
int width
int height
Private Attributes
t_gridpoint * gridpoints
class t_editor * editor
int * drawing_indices
Friends
class t_particles
Classes
struct t_interpolated_point
Detailed Description
Definition at line 60 of file grid.h.
Constructor & Destructor Documentation
t_grid::t_grid (int w, int h)
Definition at line 18 of file grid.cpp.
References rgbabcolor::a, rgbabcolor::b, t_gridpoint::color, drawing_indices, t_pgrid::editor, editor, rgbabcolor::g, t_pgrid::getinstance(), GRIDGRANULARITY, gridpoints, height, t_gridpoint::height, rgbabcolor::r, t_gridpoint::speedmod_x, t_gridpoint::speedmod_y, width, t_gridpoint::x, and t_gridpoint::y.
t_grid::~t_grid () [inline]
Definition at line 119 of file grid.h.
References drawing_indices, and gridpoints.
Member Function Documentation
int t_grid::wrap (int val, int c) [inline]
Definition at line 125 of file grid.h.
Referenced by getpoint(), and getpoint_editing().
int t_grid::clamp (int val, int c) [inline]
Definition at line 129 of file grid.h.
Referenced by getpoint().
t_gridpoint& t_grid::getpoint (int x, int y) [inline]
Definition at line 134 of file grid.h.
References clamp(), t_editor::dowrap(), editor, gridpoints, height, width, and wrap().
Referenced by phys_tick(), render_quads(), and render_quadstrips().
t_gridpoint& t_grid::getpoint_editing (int x, int y) [inline]
Definition at line 140 of file grid.h.
References t_editor::dowrap(), editor, gridpoints, height, width, and wrap().
Referenced by paint_pixels_additive(), and t_grid::t_interpolated_point::t_interpolated_point().
void t_grid::paint_pixel_additive (vec img_pos, float d) [inline]
Definition at line 148 of file grid.h.
References t_grid::t_interpolated_point::add(), and t_grid::t_interpolated_point::clamp().
Referenced by t_tool_paintgrid_singlepixel::phys_tick().
void t_grid::paint_pixels_additive (int px, int py, float * pixels, int w, int h, float amount, int stride = 0) [inline]
Definition at line 156 of file grid.h.
References getpoint_editing(), and t_gridpoint::height.
Referenced by t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), paint_pixels_additive(), and t_tool_paintgrid_spraycan::phys_tick().
void t_grid::paint_pixels_additive (vec pos, float * pixels, int w, int h, float amount, int stride = 0) [inline]
Definition at line 175 of file grid.h.
References paint_pixels_additive(), vec::x, and vec::y.
void t_grid::render_quadstrips (float img_x, float img_y, float img_w, float img_h)
Definition at line 55 of file grid.cpp.
References getpoint(), GRIDGRANULARITY, t_gridpoint::height, height, and width.
void t_grid::render_quads (float img_x, float img_y, float img_w, float img_h)
Definition at line 94 of file grid.cpp.
References getpoint(), t_gridpoint::height, height, width, t_gridpoint::x, and t_gridpoint::y.
void t_grid::render_scanlines (float img_x, float img_y, float img_w, float img_h)
Definition at line 122 of file grid.cpp.
References rgbabcolor::a, rgbabcolor::b, t_gridpoint::color, t_gridpoint::disp_height, rgbabcolor::g, gridpoints, height, t_gridpoint::looks_equal(), rgbabcolor::r, width, t_gridpoint::x, and t_gridpoint::y.
void t_grid::render_arrays (float img_x, float img_y, float img_w, float img_h)
Definition at line 248 of file grid.cpp.
References rgbabcolor::a, rgbabcolor::b, t_gridpoint::color, drawing_indices, rgbabcolor::g, gridpoints, t_gridpoint::height, height, rgbabcolor::r, and width.
Referenced by render().
void t_grid::render (float img_x, float img_y, float img_w, float img_h)
Definition at line 281 of file grid.cpp.
References render_arrays().
Referenced by t_layer::render().
void t_grid::fade (float time) [inline]
Definition at line 194 of file grid.h.
References gridpoints, height, width, and x86_fade_height().
Referenced by phys_tick().
void t_grid::phys_tick (float time) [inline]
Definition at line 208 of file grid.h.
References fade(), getpoint(), gridpoints, t_gridpoint::height, height, and width.
Referenced by t_layer::phys_tick().
Friends And Related Function Documentation
friend class t_particles [friend]
Definition at line 62 of file grid.h.
Member Data Documentation
t_gridpoint* t_grid::gridpoints [private]
Definition at line 64 of file grid.h.
Referenced by fade(), getpoint(), getpoint_editing(), phys_tick(), render_arrays(), render_scanlines(), t_grid(), and ~t_grid().
class t_editor* t_grid::editor [private]
Definition at line 65 of file grid.h.
Referenced by getpoint(), getpoint_editing(), and t_grid().
int* t_grid::drawing_indices [private]
Definition at line 66 of file grid.h.
Referenced by render_arrays(), t_grid(), and ~t_grid().
int t_grid::width
Definition at line 115 of file grid.h.
Referenced by t_particles::add(), t_particles::clamp_particle(), fade(), getpoint(), getpoint_editing(), t_particles::keyboard_event(), phys_tick(), t_workspace::printstatus(), render_arrays(), render_quads(), render_quadstrips(), render_scanlines(), and t_grid().
int t_grid::height
Definition at line 115 of file grid.h.
Referenced by t_particles::add(), t_particles::clamp_particle(), fade(), getpoint(), getpoint_editing(), t_particles::keyboard_event(), phys_tick(), t_workspace::printstatus(), render_arrays(), render_quads(), render_quadstrips(), render_scanlines(), and t_grid().
The documentation for this class was generated from the following files:
code/pgrid/src/grid.h
code/pgrid/src/grid.cpp