pgrid: t_tool_addparticles Class Reference
t_tool_addparticles Class Reference
#include <editortools.h>
Public Member Functions
t_tool_addparticles (t_editor *e)
void phys_tick (float time)
void paint ()
void erase ()
void mouse_button_event (SDL_MouseButtonEvent &evt)
void mouse_motion_event (SDL_MouseMotionEvent &evt)
void drawhint ()
Private Attributes
vec smoothedmousedelta
float radius
float amount
float amountleft
Detailed Description
Definition at line 145 of file editortools.h.
Constructor & Destructor Documentation
t_tool_addparticles::t_tool_addparticles (t_editor * e) [inline]
Definition at line 155 of file editortools.h.
References amount, amountleft, t_editortool::mouse_buttons, and radius.
Member Function Documentation
void t_tool_addparticles::phys_tick (float time) [virtual]
Reimplemented from t_editortool.
Definition at line 57 of file editortools.cpp.
References erase(), t_editortool::mouse_buttons, paint(), and t_editortool::phys_tick().
void t_tool_addparticles::paint ()
Definition at line 17 of file editortools.cpp.
References t_particles::add(), amount, amountleft, t_image::current_layer(), t_pgrid::current_workspace(), t_editortool::editor, t_editor::getbrush(), t_pgrid::getinstance(), t_brush::getwidth(), GRIDGRANULARITY, t_workspace::image, t_editortool::lerpedmousepos, vec::mul(), t_layer::particles, radius, vec::random_deviation(), and smoothedmousedelta.
Referenced by phys_tick().
void t_tool_addparticles::erase ()
Definition at line 34 of file editortools.cpp.
References amount, amountleft, t_image::current_layer(), t_pgrid::current_workspace(), t_editortool::editor, t_editor::getbrush(), t_pgrid::getinstance(), t_brush::getwidth(), GRIDGRANULARITY, t_workspace::image, t_editortool::lerpedmousepos, t_particles::particles, t_layer::particles, radius, vec::squaredlen(), and vec::sub().
Referenced by phys_tick().
void t_tool_addparticles::mouse_button_event (SDL_MouseButtonEvent & evt) [inline, virtual]
Reimplemented from t_editortool.
Definition at line 166 of file editortools.h.
References t_editortool::mouse_button_event().
void t_tool_addparticles::mouse_motion_event (SDL_MouseMotionEvent & evt) [inline, virtual]
Reimplemented from t_editortool.
Definition at line 171 of file editortools.h.
References vec::add(), t_editortool::mouse_motion_event(), vec::mul(), smoothedmousedelta, vec::x, and vec::y.
void t_tool_addparticles::drawhint () [inline]
Definition at line 180 of file editortools.h.
Member Data Documentation
vec t_tool_addparticles::smoothedmousedelta [private]
Definition at line 148 of file editortools.h.
Referenced by mouse_motion_event(), and paint().
float t_tool_addparticles::radius [private]
Definition at line 150 of file editortools.h.
Referenced by erase(), paint(), and t_tool_addparticles().
float t_tool_addparticles::amount [private]
Definition at line 151 of file editortools.h.
Referenced by erase(), paint(), and t_tool_addparticles().
float t_tool_addparticles::amountleft [private]
Definition at line 152 of file editortools.h.
Referenced by erase(), paint(), and t_tool_addparticles().
The documentation for this class was generated from the following files:
code/pgrid/src/editortools.h
code/pgrid/src/editortools.cpp