pgrid: t_workspace Class Reference
t_workspace Class Reference
#include <workspace.h>
Public Member Functions
t_workspace (t_pgrid *_pgrid)
~t_workspace ()
float getzoom ()
vec screen2img (int x, int y)
vec img2screen (float x, float y)
void centerimage ()
void renderbg ()
void render ()
void setcenter (float img_cx, float img_cy)
void dozoom (float factor, bool mousecenter=false)
void printstatus ()
void keyboard_event (SDL_KeyboardEvent &event)
void mouse_motion_event (SDL_MouseMotionEvent &event)
void mouse_button_event (SDL_MouseButtonEvent &evt)
Public Attributes
class t_pgrid * pgrid
class t_image * image
Private Attributes
float zoom
vec img
bool dragging
u32 dragstart
vec dragstartpos
Static Private Attributes
static t_texture * bgtexture
Detailed Description
Definition at line 9 of file workspace.h.
Constructor & Destructor Documentation
t_workspace::t_workspace (t_pgrid * _pgrid) [inline]
Definition at line 23 of file workspace.h.
References bgtexture, centerimage(), image, t_image::t_image(), and tsize.
t_workspace::~t_workspace () [inline]
Definition at line 53 of file workspace.h.
References image.
Member Function Documentation
float t_workspace::getzoom () [inline]
Definition at line 58 of file workspace.h.
References zoom.
Referenced by t_editortool::phys_tick().
vec t_workspace::screen2img (int x, int y) [inline]
Definition at line 60 of file workspace.h.
References img, vec::x, vec::y, and zoom.
Referenced by dozoom(), mouse_button_event(), t_editortool::mouse_button_event(), t_editortool::mouse_motion_event(), and t_editortool::phys_tick().
vec t_workspace::img2screen (float x, float y) [inline]
Definition at line 66 of file workspace.h.
References img, vec::x, vec::y, and zoom.
void t_workspace::centerimage () [inline]
Definition at line 72 of file workspace.h.
References t_screen::height, t_image::height, image, img, pgrid, t_pgrid::screen, t_screen::width, t_image::width, vec::x, vec::y, and zoom.
Referenced by keyboard_event(), t_pgrid::run(), and t_workspace().
void t_workspace::renderbg () [inline]
Definition at line 80 of file workspace.h.
References bgtexture, t_texture::bind(), t_screen::height, t_texture::height, img, pgrid, t_pgrid::screen, t_screen::width, t_texture::width, vec::x, vec::y, and zoom.
Referenced by render().
void t_workspace::render () [inline]
Definition at line 102 of file workspace.h.
References t_image::height, t_screen::height, image, img, t_screen::ortho, pgrid, t_screen::planedist, t_image::render(), renderbg(), t_pgrid::screen, t_image::width, t_screen::width, vec::x, vec::y, and zoom.
Referenced by t_pgrid::run().
void t_workspace::setcenter (float img_cx, float img_cy) [inline]
Definition at line 126 of file workspace.h.
References t_screen::height, img, pgrid, t_pgrid::screen, t_screen::width, vec::x, vec::y, and zoom.
Referenced by dozoom(), and mouse_button_event().
void t_workspace::dozoom (float factor, bool mousecenter = false) [inline]
Definition at line 132 of file workspace.h.
References t_screen::height, t_pgrid::mouse, pgrid, t_pgrid::screen, screen2img(), setcenter(), t_screen::width, vec::x, vec::y, and zoom.
Referenced by keyboard_event(), and mouse_button_event().
void t_workspace::printstatus () [inline]
Definition at line 145 of file workspace.h.
References t_image::current_layer(), t_layer::grid, t_grid::height, image, t_particles::particles, t_layer::particles, and t_grid::width.
Referenced by keyboard_event().
void t_workspace::keyboard_event (SDL_KeyboardEvent & event) [inline, virtual]
Implements input_handler.
Definition at line 151 of file workspace.h.
References centerimage(), dozoom(), t_pgrid::getkeystate(), image, img, t_screen::ortho, pgrid, printstatus(), t_pgrid::screen, t_screen::setortho(), t_screen::setperspective(), t_image::showgrid, t_screen::togglefullscreen(), vec::x, and vec::y.
Referenced by t_pgrid::run().
void t_workspace::mouse_motion_event (SDL_MouseMotionEvent & event) [inline, virtual]
Implements input_handler.
Definition at line 174 of file workspace.h.
References vec::add(), dragging, and img.
Referenced by t_pgrid::run().
void t_workspace::mouse_button_event (SDL_MouseButtonEvent & evt) [inline, virtual]
Implements input_handler.
Definition at line 183 of file workspace.h.
References dozoom(), dragging, dragstart, dragstartpos, t_pgrid::getkeystate(), vec::len(), t_pgrid::mouse, pgrid, screen2img(), setcenter(), vec::sub(), t_pgrid::time(), vec::x, and vec::y.
Referenced by t_pgrid::run().
Member Data Documentation
float t_workspace::zoom [private]
Definition at line 12 of file workspace.h.
Referenced by centerimage(), dozoom(), getzoom(), img2screen(), render(), renderbg(), screen2img(), and setcenter().
vec t_workspace::img [private]
Definition at line 13 of file workspace.h.
Referenced by centerimage(), img2screen(), keyboard_event(), mouse_motion_event(), render(), renderbg(), screen2img(), and setcenter().
bool t_workspace::dragging [private]
Definition at line 14 of file workspace.h.
Referenced by mouse_button_event(), and mouse_motion_event().
u32 t_workspace::dragstart [private]
Definition at line 15 of file workspace.h.
Referenced by mouse_button_event().
vec t_workspace::dragstartpos [private]
Definition at line 16 of file workspace.h.
Referenced by mouse_button_event().
t_texture * t_workspace::bgtexture [static, private]
Definition at line 17 of file workspace.h.
Referenced by renderbg(), and t_workspace().
class t_pgrid* t_workspace::pgrid
Definition at line 20 of file workspace.h.
Referenced by centerimage(), dozoom(), keyboard_event(), mouse_button_event(), render(), renderbg(), and setcenter().
class t_image* t_workspace::image
Definition at line 21 of file workspace.h.
Referenced by centerimage(), t_tool_addparticles::erase(), t_particles::iscurrent(), keyboard_event(), t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), t_tool_addparticles::paint(), t_tool_paintgrid_spraycan::phys_tick(), t_tool_paintgrid_singlepixel::phys_tick(), printstatus(), render(), t_pgrid::runphysics(), t_workspace(), and ~t_workspace().
The documentation for this class was generated from the following files:
code/pgrid/src/workspace.h
code/pgrid/src/workspace.cpp