pgrid: t_image Class Reference
t_image Class Reference
#include <image.h>
Public Member Functions
t_image (t_workspace *_workspace)
t_layer * current_layer ()
void render (float x, float y, float w, float h)
void phys_tick (float time)
Public Attributes
int width
int height
bool showgrid
class t_workspace * workspace
Private Attributes
std::vector< t_layer * > layers
Detailed Description
Definition at line 9 of file image.h.
Constructor & Destructor Documentation
t_image::t_image (t_workspace * _workspace) [inline]
Definition at line 19 of file image.h.
References layers.
Referenced by t_workspace::t_workspace().
Member Function Documentation
t_layer* t_image::current_layer () [inline]
Definition at line 24 of file image.h.
References layers.
Referenced by t_tool_addparticles::erase(), t_particles::iscurrent(), t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), t_tool_addparticles::paint(), t_tool_paintgrid_spraycan::phys_tick(), t_tool_paintgrid_singlepixel::phys_tick(), and t_workspace::printstatus().
void t_image::render (float x, float y, float w, float h) [inline]
Definition at line 29 of file image.h.
References layers.
Referenced by t_workspace::render().
void t_image::phys_tick (float time) [inline]
Definition at line 35 of file image.h.
References layers.
Referenced by t_pgrid::runphysics().
Member Data Documentation
std::vector<t_layer *> t_image::layers [private]
Definition at line 12 of file image.h.
Referenced by current_layer(), phys_tick(), render(), and t_image().
int t_image::width
Definition at line 15 of file image.h.
Referenced by t_workspace::centerimage(), t_workspace::render(), and t_layer::t_layer().
int t_image::height
Definition at line 15 of file image.h.
Referenced by t_workspace::centerimage(), t_workspace::render(), and t_layer::t_layer().
bool t_image::showgrid
Definition at line 16 of file image.h.
Referenced by t_workspace::keyboard_event(), and t_layer::render().
class t_workspace* t_image::workspace
Definition at line 17 of file image.h.
The documentation for this class was generated from the following file:
code/pgrid/src/image.h