pgrid: dyninputhandler Class Reference
dyninputhandler Class Reference
#include <main.h>
Public Member Functions
dyninputhandler ()
~dyninputhandler ()
virtual void keyboard_event (SDL_KeyboardEvent &evt)
virtual void mouse_motion_event (SDL_MouseMotionEvent &evt)
virtual void mouse_button_event (SDL_MouseButtonEvent &evt)
Detailed Description
Definition at line 106 of file main.h.
Constructor & Destructor Documentation
dyninputhandler::dyninputhandler ()
Definition at line 156 of file pgrid.cpp.
References t_pgrid::getinstance(), and t_pgrid::registerinputhandler().
dyninputhandler::~dyninputhandler ()
Definition at line 160 of file pgrid.cpp.
References t_pgrid::getinstance(), and t_pgrid::unregisterinputhandler().
Member Function Documentation
virtual void dyninputhandler::keyboard_event (SDL_KeyboardEvent & evt) [inline, virtual]
Implements input_handler.
Reimplemented in t_particles.
Definition at line 112 of file main.h.
virtual void dyninputhandler::mouse_motion_event (SDL_MouseMotionEvent & evt) [inline, virtual]
Implements input_handler.
Definition at line 113 of file main.h.
virtual void dyninputhandler::mouse_button_event (SDL_MouseButtonEvent & evt) [inline, virtual]
Implements input_handler.
Definition at line 114 of file main.h.
The documentation for this class was generated from the following files:
code/pgrid/src/main.h
code/pgrid/src/pgrid.cpp