pgrid: t_tool_paintgrid_brush Class Reference
t_tool_paintgrid_brush Class Reference
#include <editortools.h>
Public Member Functions
t_tool_paintgrid_brush (t_editor *e)
void phys_tick (float time)
void mousepaint ()
void mouse_button_event (SDL_MouseButtonEvent &evt)
void mouse_motion_event (SDL_MouseMotionEvent &evt)
void drawhint ()
Private Attributes
float intensity
Detailed Description
Definition at line 79 of file editortools.h.
Constructor & Destructor Documentation
t_tool_paintgrid_brush::t_tool_paintgrid_brush (t_editor * e) [inline]
Definition at line 85 of file editortools.h.
References t_editortool::mouse_buttons.
Member Function Documentation
void t_tool_paintgrid_brush::phys_tick (float time) [inline, virtual]
Reimplemented from t_editortool.
Definition at line 90 of file editortools.h.
References t_editortool::phys_tick().
void t_tool_paintgrid_brush::mousepaint () [inline]
Definition at line 95 of file editortools.h.
References t_image::current_layer(), t_pgrid::current_workspace(), t_editortool::editor, t_editor::getbrush(), t_brush::getheight(), t_pgrid::getinstance(), t_brush::getpixels(), t_brush::getwidth(), t_layer::grid, GRIDGRANULARITY, t_workspace::image, intensity, t_editortool::lerpedmousepos, t_editortool::mouse_buttons, vec::mul(), t_grid::paint_pixels_additive(), vec::x, and vec::y.
Referenced by mouse_button_event(), and mouse_motion_event().
void t_tool_paintgrid_brush::mouse_button_event (SDL_MouseButtonEvent & evt) [inline, virtual]
Reimplemented from t_editortool.
Definition at line 103 of file editortools.h.
References t_editortool::mouse_button_event(), t_editortool::mouse_buttons, and mousepaint().
void t_tool_paintgrid_brush::mouse_motion_event (SDL_MouseMotionEvent & evt) [inline, virtual]
Reimplemented from t_editortool.
Definition at line 109 of file editortools.h.
References t_editortool::mouse_buttons, t_editortool::mouse_motion_event(), and mousepaint().
void t_tool_paintgrid_brush::drawhint () [inline]
Definition at line 115 of file editortools.h.
Member Data Documentation
float t_tool_paintgrid_brush::intensity [private]
Definition at line 82 of file editortools.h.
Referenced by mousepaint().
The documentation for this class was generated from the following file:
code/pgrid/src/editortools.h