pgrid: t_blobbrush Class Reference
t_blobbrush Class Reference
#include <brush.h>
Public Member Functions
void create (int width, int height, float sharpness=0.0)
t_blobbrush (int width, int height, float sharpness=0.0)
float getsharpness ()
void resize (int width, int height)
Private Attributes
float sharpness
Detailed Description
Definition at line 29 of file brush.h.
Constructor & Destructor Documentation
t_blobbrush::t_blobbrush (int width, int height, float sharpness = 0.0) [inline]
Definition at line 47 of file brush.h.
References create(), and sharpness.
Member Function Documentation
void t_blobbrush::create (int width, int height, float sharpness = 0.0) [inline]
Definition at line 35 of file brush.h.
References BRUSHTYPE_BLOB, mkblobf, t_brush::pixels, sharpness, and t_brush::type.
Referenced by resize(), and t_blobbrush().
float t_blobbrush::getsharpness () [inline]
Definition at line 52 of file brush.h.
References sharpness.
void t_blobbrush::resize (int width, int height) [inline, virtual]
Implements t_brush.
Definition at line 54 of file brush.h.
References create(), and sharpness.
Member Data Documentation
float t_blobbrush::sharpness [private]
Definition at line 32 of file brush.h.
Referenced by create(), getsharpness(), resize(), and t_blobbrush().
The documentation for this class was generated from the following file:
code/pgrid/src/brush.h