pgrid: t_tool_push Class Reference
t_tool_push Class Reference
#include <editortools.h>
Public Member Functions
t_tool_push (t_editor *e)
void phys_tick (float time)
void mousepaint ()
void mouse_button_event (SDL_MouseButtonEvent &evt)
void mouse_motion_event (SDL_MouseMotionEvent &evt)
void drawhint ()
Private Attributes
float intensity
Detailed Description
Definition at line 120 of file editortools.h.
Constructor & Destructor Documentation
t_tool_push::t_tool_push (t_editor * e) [inline]
Definition at line 126 of file editortools.h.
References t_editortool::mouse_buttons.
Member Function Documentation
void t_tool_push::phys_tick (float time) [inline, virtual]
Reimplemented from t_editortool.
Definition at line 131 of file editortools.h.
References t_editortool::phys_tick().
void t_tool_push::mousepaint ()
Definition at line 71 of file editortools.cpp.
References t_image::current_layer(), t_pgrid::current_workspace(), t_editortool::editor, t_editor::getbrush(), t_brush::getheight(), t_pgrid::getinstance(), t_brush::getpixels(), t_brush::getwidth(), t_layer::grid, GRIDGRANULARITY, t_workspace::image, intensity, t_editortool::lerpedmousepos, t_editortool::mouse_buttons, vec::mul(), t_grid::paint_pixels_additive(), vec::x, and vec::y.
Referenced by mouse_button_event(), and mouse_motion_event().
void t_tool_push::mouse_button_event (SDL_MouseButtonEvent & evt) [virtual]
Reimplemented from t_editortool.
Definition at line 79 of file editortools.cpp.
References t_editortool::mouse_button_event(), t_editortool::mouse_buttons, and mousepaint().
void t_tool_push::mouse_motion_event (SDL_MouseMotionEvent & evt) [virtual]
Reimplemented from t_editortool.
Definition at line 85 of file editortools.cpp.
References t_editortool::mouse_buttons, t_editortool::mouse_motion_event(), and mousepaint().
void t_tool_push::drawhint ()
Definition at line 91 of file editortools.cpp.
Member Data Documentation
float t_tool_push::intensity [private]
Definition at line 123 of file editortools.h.
Referenced by mousepaint().
The documentation for this class was generated from the following files:
code/pgrid/src/editortools.h
code/pgrid/src/editortools.cpp