pgrid: t_editortool Class Reference
t_editortool Class Reference
#include <editortool.h>
Public Member Functions
t_editortool (t_editor *e)
void keyboard_event (SDL_KeyboardEvent &evt)
void mouse_motion_event (SDL_MouseMotionEvent &evt)
void mouse_button_event (SDL_MouseButtonEvent &evt)
virtual void phys_tick (float time)
virtual void drawhint (vec &img_pos)
Protected Attributes
class t_editor * editor
int mouse_buttons
vec mouse_img_pos
vec lastmousemove
vec lerpedmousepos
Detailed Description
Definition at line 6 of file editortool.h.
Constructor & Destructor Documentation
t_editortool::t_editortool (t_editor * e) [inline]
Definition at line 16 of file editortool.h.
References mouse_img_pos, vec::x, and vec::y.
Member Function Documentation
void t_editortool::keyboard_event (SDL_KeyboardEvent & evt) [inline, virtual]
Implements input_handler.
Definition at line 21 of file editortool.h.
void t_editortool::mouse_motion_event (SDL_MouseMotionEvent & evt) [virtual]
Implements input_handler.
Reimplemented in t_tool_paintgrid_brush, t_tool_push, and t_tool_addparticles.
Definition at line 35 of file editor.cpp.
References t_pgrid::current_workspace(), t_pgrid::getinstance(), lastmousemove, mouse_buttons, mouse_img_pos, t_workspace::screen2img(), vec::x, and vec::y.
Referenced by t_tool_addparticles::mouse_motion_event(), t_tool_paintgrid_brush::mouse_motion_event(), t_tool_push::mouse_motion_event(), and t_editor::mouse_motion_event().
void t_editortool::mouse_button_event (SDL_MouseButtonEvent & evt) [virtual]
Implements input_handler.
Reimplemented in t_tool_paintgrid_brush, t_tool_push, and t_tool_addparticles.
Definition at line 42 of file editor.cpp.
References t_pgrid::current_workspace(), t_pgrid::getinstance(), mouse_buttons, mouse_img_pos, and t_workspace::screen2img().
Referenced by t_tool_addparticles::mouse_button_event(), t_tool_paintgrid_brush::mouse_button_event(), t_tool_push::mouse_button_event(), and t_editor::mouse_button_event().
void t_editortool::phys_tick (float time) [virtual]
Reimplemented in t_tool_paintgrid_singlepixel, t_tool_paintgrid_spraycan, t_tool_paintgrid_brush, t_tool_push, and t_tool_addparticles.
Definition at line 49 of file editor.cpp.
References vec::add(), t_pgrid::current_workspace(), editor, t_pgrid::framephystime(), t_pgrid::getinstance(), t_pgrid::getmousevel(), t_workspace::getzoom(), lerpedmousepos, t_editor::lerpmouse, mouse_img_pos, t_pgrid::mousepos, vec::mul(), t_pgrid::phystime(), t_workspace::screen2img(), vec::x, and vec::y.
Referenced by t_tool_push::phys_tick(), t_tool_paintgrid_brush::phys_tick(), t_tool_paintgrid_spraycan::phys_tick(), t_tool_paintgrid_singlepixel::phys_tick(), t_tool_addparticles::phys_tick(), and t_editor::phys_tick().
virtual void t_editortool::drawhint (vec & img_pos) [inline, virtual]
Definition at line 26 of file editortool.h.
Member Data Documentation
class t_editor* t_editortool::editor [protected]
Definition at line 9 of file editortool.h.
Referenced by t_tool_addparticles::erase(), t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), t_tool_addparticles::paint(), t_tool_paintgrid_spraycan::phys_tick(), and phys_tick().
int t_editortool::mouse_buttons [protected]
Definition at line 10 of file editortool.h.
Referenced by t_tool_paintgrid_brush::mouse_button_event(), t_tool_push::mouse_button_event(), mouse_button_event(), t_tool_paintgrid_brush::mouse_motion_event(), t_tool_push::mouse_motion_event(), mouse_motion_event(), t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), t_tool_paintgrid_spraycan::phys_tick(), t_tool_paintgrid_singlepixel::phys_tick(), t_tool_addparticles::phys_tick(), t_tool_addparticles::t_tool_addparticles(), t_tool_paintgrid_brush::t_tool_paintgrid_brush(), t_tool_paintgrid_singlepixel::t_tool_paintgrid_singlepixel(), t_tool_paintgrid_spraycan::t_tool_paintgrid_spraycan(), and t_tool_push::t_tool_push().
vec t_editortool::mouse_img_pos [protected]
Definition at line 11 of file editortool.h.
Referenced by mouse_button_event(), mouse_motion_event(), t_tool_paintgrid_spraycan::phys_tick(), t_tool_paintgrid_singlepixel::phys_tick(), phys_tick(), and t_editortool().
vec t_editortool::lastmousemove [protected]
Definition at line 12 of file editortool.h.
Referenced by mouse_motion_event().
vec t_editortool::lerpedmousepos [protected]
Definition at line 13 of file editortool.h.
Referenced by t_tool_addparticles::erase(), t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), t_tool_addparticles::paint(), and phys_tick().
The documentation for this class was generated from the following files:
code/pgrid/src/editortool.h
code/pgrid/src/editor.cpp