pgrid: t_tool_paintgrid_spraycan Class Reference
t_tool_paintgrid_spraycan Class Reference
#include <editortools.h>
Public Member Functions
t_tool_paintgrid_spraycan (t_editor *e)
void phys_tick (float time)
void drawhint ()
Private Attributes
float intensity
float radius
int amount
Detailed Description
Definition at line 43 of file editortools.h.
Constructor & Destructor Documentation
t_tool_paintgrid_spraycan::t_tool_paintgrid_spraycan (t_editor * e) [inline]
Definition at line 51 of file editortools.h.
References t_editortool::mouse_buttons.
Member Function Documentation
void t_tool_paintgrid_spraycan::phys_tick (float time) [inline, virtual]
Reimplemented from t_editortool.
Definition at line 56 of file editortools.h.
References amount, t_image::current_layer(), t_pgrid::current_workspace(), t_editortool::editor, t_editor::getbrush(), t_brush::getheight(), t_pgrid::getinstance(), t_brush::getpixels(), t_brush::getwidth(), t_layer::grid, GRIDGRANULARITY, t_workspace::image, intensity, t_editortool::mouse_buttons, t_editortool::mouse_img_pos, vec::mul(), t_grid::paint_pixels_additive(), t_editortool::phys_tick(), radius, vec::random_deviation(), vec::x, and vec::y.
void t_tool_paintgrid_spraycan::drawhint () [inline]
Definition at line 74 of file editortools.h.
Member Data Documentation
float t_tool_paintgrid_spraycan::intensity [private]
Definition at line 46 of file editortools.h.
Referenced by phys_tick().
float t_tool_paintgrid_spraycan::radius [private]
Definition at line 47 of file editortools.h.
Referenced by phys_tick().
int t_tool_paintgrid_spraycan::amount [private]
Definition at line 48 of file editortools.h.
Referenced by phys_tick().
The documentation for this class was generated from the following file:
code/pgrid/src/editortools.h