pgrid: t_particles Class Reference
t_particles Class Reference
#include <particles.h>
Public Types
typedef vector
< t_particle > t_particlecontainer
Public Member Functions
t_particles (t_grid *g)
~t_particles ()
void keyboard_event (SDL_KeyboardEvent &evt)
void phys_tick (float time)
void render (float x, float y, float w, float h)
void add (t_particle &p)
void clamp_particle (t_particle &p)
Public Attributes
t_grid * grid
t_editor * editor
t_particlecontainer particles
t_texture * texture
Private Member Functions
void renderquads ()
void renderarrays ()
void updatearrays ()
void complexphysics (float time)
bool iscurrent ()
Private Attributes
t_quadarray quadarray
float nextcomplexphysics
Static Private Attributes
static int rendermode
Classes
struct t_quadarray
Detailed Description
Definition at line 20 of file particles.h.
Member Typedef Documentation
typedef vector<t_particle> t_particles::t_particlecontainer
Definition at line 52 of file particles.h.
Constructor & Destructor Documentation
t_particles::t_particles (t_grid * g)
Definition at line 25 of file particles.cpp.
References t_pgrid::editor, editor, t_pgrid::getinstance(), mkblobu8, nextcomplexphysics, texture, and tsize.
t_particles::~t_particles ()
Definition at line 39 of file particles.cpp.
Member Function Documentation
void t_particles::renderquads () [private]
Definition at line 122 of file particles.cpp.
References t_particle::height, particles, t_particle::pos, vector< T >::size(), vec::x, and vec::y.
Referenced by render().
void t_particles::renderarrays () [private]
Definition at line 158 of file particles.cpp.
References t_particles::t_quadarray::draw(), and quadarray.
Referenced by render().
void t_particles::updatearrays () [private]
Definition at line 143 of file particles.cpp.
References t_particles::t_quadarray::alloc(), t_particle::height, t_particles::t_quadarray::nquads, particles, t_particle::pos, quadarray, vector< T >::size(), t_particles::t_quadarray::updatequad(), vec::x, and vec::y.
Referenced by keyboard_event().
void t_particles::complexphysics (float time) [private]
Definition at line 63 of file particles.cpp.
References t_grid::t_interpolated_point::add(), vec::add(), t_particles::t_quadarray::alloc(), clamp_particle(), t_grid::t_interpolated_point::dx, t_grid::t_interpolated_point::dy, grid, t_particle::height, t_gridpoint::height, t_gridpoint::IDX_HEIGHT, t_gridpoint::IDX_SPEEDMOD_X, t_gridpoint::IDX_SPEEDMOD_Y, t_grid::t_interpolated_point::lerp(), vec::mul(), particles, t_particle::pos, quadarray, vec::random_deviation(), vector< T >::size(), t_particle::speed, vec::squaredlen(), t_grid::t_interpolated_point::v0, t_grid::t_interpolated_point::v1, t_grid::t_interpolated_point::v2, t_grid::t_interpolated_point::v3, vec::x, and vec::y.
Referenced by phys_tick().
bool t_particles::iscurrent () [private]
Definition at line 20 of file particles.cpp.
References t_image::current_layer(), t_pgrid::current_workspace(), t_pgrid::getinstance(), grid, t_layer::grid, and t_workspace::image.
Referenced by keyboard_event().
void t_particles::keyboard_event (SDL_KeyboardEvent & evt) [virtual]
Reimplemented from dyninputhandler.
Definition at line 184 of file particles.cpp.
References vector< T >::add(), grid, GRIDGRANULARITY, t_grid::height, iscurrent(), particles, rendermode, rnd(), vector< T >::setsize_fast(), updatearrays(), and t_grid::width.
void t_particles::phys_tick (float time)
Definition at line 109 of file particles.cpp.
References complexphysics(), and nextcomplexphysics.
Referenced by t_layer::phys_tick().
void t_particles::render (float x, float y, float w, float h)
Definition at line 165 of file particles.cpp.
References t_texture::bind(), editor, renderarrays(), rendermode, renderquads(), t_editor::showparticles, and texture.
Referenced by t_layer::render().
void t_particles::add (t_particle & p)
Definition at line 44 of file particles.cpp.
References vector< T >::add(), t_editor::dowrap(), editor, grid, GRIDGRANULARITY, t_grid::height, particles, t_particle::pos, t_grid::width, vec::x, and vec::y.
Referenced by t_tool_addparticles::paint().
void t_particles::clamp_particle (t_particle & p) [inline]
Definition at line 70 of file particles.h.
References t_editor::dowrap(), editor, grid, GRIDGRANULARITY, t_grid::height, t_particle::pos, t_particle::speed, t_grid::width, vec::x, and vec::y.
Referenced by complexphysics().
Member Data Documentation
int t_particles::rendermode [static, private]
Definition at line 29 of file particles.h.
Referenced by keyboard_event(), and render().
t_quadarray t_particles::quadarray [private]
Definition at line 47 of file particles.h.
Referenced by complexphysics(), renderarrays(), and updatearrays().
float t_particles::nextcomplexphysics [private]
Definition at line 49 of file particles.h.
Referenced by phys_tick(), and t_particles().
t_grid* t_particles::grid
Definition at line 54 of file particles.h.
Referenced by add(), clamp_particle(), complexphysics(), iscurrent(), and keyboard_event().
t_editor* t_particles::editor
Definition at line 55 of file particles.h.
Referenced by add(), clamp_particle(), render(), and t_particles().
t_particlecontainer t_particles::particles
Definition at line 56 of file particles.h.
Referenced by add(), complexphysics(), t_tool_addparticles::erase(), keyboard_event(), t_workspace::printstatus(), renderquads(), and updatearrays().
t_texture* t_particles::texture
Definition at line 57 of file particles.h.
Referenced by render(), and t_particles().
The documentation for this class was generated from the following files:
code/pgrid/src/particles.h
code/pgrid/src/particles.cpp