pgrid: t_brush Class Reference
t_brush Class Reference
#include <brush.h>
Public Member Functions
t_brush ()
virtual ~t_brush ()
float * getpixels ()
int getwidth ()
int getheight ()
virtual void resize (int width, int height)=0
Protected Attributes
int width
int height
float * pixels
int type
Detailed Description
Definition at line 10 of file brush.h.
Constructor & Destructor Documentation
t_brush::t_brush () [inline]
Definition at line 18 of file brush.h.
virtual t_brush::~t_brush () [inline, virtual]
Definition at line 19 of file brush.h.
References pixels.
Member Function Documentation
float* t_brush::getpixels () [inline]
Definition at line 21 of file brush.h.
References pixels.
Referenced by t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), and t_tool_paintgrid_spraycan::phys_tick().
int t_brush::getwidth () [inline]
Definition at line 22 of file brush.h.
References width.
Referenced by t_tool_addparticles::erase(), t_editor::keyboard_event(), t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), t_tool_addparticles::paint(), and t_tool_paintgrid_spraycan::phys_tick().
int t_brush::getheight () [inline]
Definition at line 23 of file brush.h.
References height.
Referenced by t_editor::keyboard_event(), t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), and t_tool_paintgrid_spraycan::phys_tick().
virtual void t_brush::resize (int width, int height) [pure virtual]
Implemented in t_blobbrush.
Referenced by t_editor::keyboard_event().
Member Data Documentation
int t_brush::width [protected]
Definition at line 13 of file brush.h.
Referenced by getwidth().
int t_brush::height [protected]
Definition at line 13 of file brush.h.
Referenced by getheight().
float* t_brush::pixels [protected]
Definition at line 14 of file brush.h.
Referenced by t_blobbrush::create(), getpixels(), and ~t_brush().
int t_brush::type [protected]
Definition at line 15 of file brush.h.
Referenced by t_blobbrush::create().
The documentation for this class was generated from the following file:
code/pgrid/src/brush.h