pgrid: t_pgrid Class Reference
t_pgrid Class Reference
#include <pgrid.h>
Public Types
enum { PHYSICSFRAMEMILLIS = 1000/100 }
Public Member Functions
t_pgrid ()
~t_pgrid ()
t_workspace * current_workspace ()
u32 time ()
u32 frametime ()
u32 phystime ()
u32 framephystime ()
vec & getmousevel ()
bool getkeystate (SDLKey key)
void registerinputhandler (dyninputhandler *h)
void unregisterinputhandler (dyninputhandler *h)
void run ()
Static Public Member Functions
static t_pgrid * getinstance ()
Public Attributes
vec mousepos
t_screen screen
class t_editor * editor
t_pgrid::_mouse mouse
Private Types
typedef std::set
< dyninputhandler * > t_dyninputhandler_list
Private Member Functions
void runphysics ()
Private Attributes
u32 lastmillis
u32 curmillis
u32 physicstime
u32 lastframephystime
std::vector< class
t_workspace * > workspaces
u8 keystate [SDLK_LAST]
vec mousevel
t_dyninputhandler_list dyninputhandlers
Static Private Attributes
static t_pgrid * instance
Classes
struct _mouse
Detailed Description
Definition at line 9 of file pgrid.h.
Member Typedef Documentation
typedef std::set<dyninputhandler*> t_pgrid::t_dyninputhandler_list [private]
Definition at line 18 of file pgrid.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
PHYSICSFRAMEMILLIS
Definition at line 26 of file pgrid.h.
Constructor & Destructor Documentation
t_pgrid::t_pgrid ()
Definition at line 18 of file pgrid.cpp.
References editor, t_screen::init(), instance, physicstime, screen, and workspaces.
Referenced by getinstance().
t_pgrid::~t_pgrid ()
Definition at line 35 of file pgrid.cpp.
References editor, instance, and workspaces.
Member Function Documentation
void t_pgrid::runphysics () [private]
Definition at line 43 of file pgrid.cpp.
References curmillis, current_workspace(), editor, t_workspace::image, t_image::phys_tick(), t_editor::phys_tick(), PHYSICSFRAMEMILLIS, physicstime, and time().
Referenced by run().
t_pgrid * t_pgrid::getinstance () [static]
Definition at line 149 of file pgrid.cpp.
References instance, and t_pgrid().
Referenced by dyninputhandler::dyninputhandler(), t_tool_addparticles::erase(), t_particles::iscurrent(), main(), t_editortool::mouse_button_event(), t_editortool::mouse_motion_event(), t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), t_tool_addparticles::paint(), t_tool_paintgrid_spraycan::phys_tick(), t_tool_paintgrid_singlepixel::phys_tick(), t_editortool::phys_tick(), t_grid::t_grid(), t_particles::t_particles(), t_texture::t_texture(), dyninputhandler::~dyninputhandler(), and t_texture::~t_texture().
t_workspace* t_pgrid::current_workspace () [inline]
Definition at line 39 of file pgrid.h.
References workspaces.
Referenced by t_tool_addparticles::erase(), t_particles::iscurrent(), t_editortool::mouse_button_event(), t_editortool::mouse_motion_event(), t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), t_tool_addparticles::paint(), t_tool_paintgrid_spraycan::phys_tick(), t_tool_paintgrid_singlepixel::phys_tick(), t_editortool::phys_tick(), run(), and runphysics().
u32 t_pgrid::time () [inline]
Definition at line 44 of file pgrid.h.
References curmillis.
Referenced by t_workspace::mouse_button_event(), and runphysics().
u32 t_pgrid::frametime () [inline]
Definition at line 49 of file pgrid.h.
References curmillis, and lastmillis.
u32 t_pgrid::phystime () [inline]
Definition at line 54 of file pgrid.h.
References physicstime.
Referenced by t_editortool::phys_tick().
u32 t_pgrid::framephystime () [inline]
Definition at line 56 of file pgrid.h.
References lastframephystime.
Referenced by t_editortool::phys_tick().
vec& t_pgrid::getmousevel () [inline]
Definition at line 58 of file pgrid.h.
References mousevel.
Referenced by t_editortool::phys_tick().
bool t_pgrid::getkeystate (SDLKey key) [inline]
Definition at line 60 of file pgrid.h.
References keystate.
Referenced by t_workspace::keyboard_event(), and t_workspace::mouse_button_event().
void t_pgrid::registerinputhandler (dyninputhandler * h) [inline]
Definition at line 65 of file pgrid.h.
References dyninputhandlers.
Referenced by dyninputhandler::dyninputhandler().
void t_pgrid::unregisterinputhandler (dyninputhandler * h) [inline]
Definition at line 66 of file pgrid.h.
References dyninputhandlers.
Referenced by dyninputhandler::~dyninputhandler().
void t_pgrid::run ()
Definition at line 55 of file pgrid.cpp.
References t_pgrid::_mouse::buttons, t_workspace::centerimage(), checkglerror(), curmillis, current_workspace(), dyninputhandlers, editor, t_screen::gl_init(), t_editor::keyboard_event(), t_workspace::keyboard_event(), keystate, lastframephystime, lastmillis, mouse, t_editor::mouse_button_event(), t_workspace::mouse_button_event(), t_editor::mouse_motion_event(), t_workspace::mouse_motion_event(), mousepos, mousevel, vec::mul(), physicstime, t_workspace::render(), runphysics(), screen, t_screen::sdl_surface, vec::x, and vec::y.
Referenced by main().
Member Data Documentation
t_pgrid * t_pgrid::instance [static, private]
Definition at line 12 of file pgrid.h.
Referenced by getinstance(), t_pgrid(), and ~t_pgrid().
u32 t_pgrid::lastmillis [private]
Definition at line 13 of file pgrid.h.
Referenced by frametime(), and run().
u32 t_pgrid::curmillis [private]
Definition at line 13 of file pgrid.h.
Referenced by frametime(), run(), runphysics(), and time().
u32 t_pgrid::physicstime [private]
Definition at line 14 of file pgrid.h.
Referenced by phystime(), run(), runphysics(), and t_pgrid().
u32 t_pgrid::lastframephystime [private]
Definition at line 14 of file pgrid.h.
Referenced by framephystime(), and run().
std::vector<class t_workspace *> t_pgrid::workspaces [private]
Definition at line 15 of file pgrid.h.
Referenced by current_workspace(), t_pgrid(), and ~t_pgrid().
u8 t_pgrid::keystate[SDLK_LAST] [private]
Definition at line 16 of file pgrid.h.
Referenced by getkeystate(), and run().
vec t_pgrid::mousevel [private]
Definition at line 17 of file pgrid.h.
Referenced by getmousevel(), and run().
t_dyninputhandler_list t_pgrid::dyninputhandlers [private]
Definition at line 19 of file pgrid.h.
Referenced by registerinputhandler(), run(), and unregisterinputhandler().
vec t_pgrid::mousepos
Definition at line 24 of file pgrid.h.
Referenced by t_editortool::phys_tick(), and run().
t_screen t_pgrid::screen
Definition at line 28 of file pgrid.h.
Referenced by t_workspace::centerimage(), t_workspace::dozoom(), t_workspace::keyboard_event(), t_workspace::render(), t_workspace::renderbg(), run(), t_workspace::setcenter(), t_pgrid(), t_texture::t_texture(), and t_texture::~t_texture().
class t_editor* t_pgrid::editor
Definition at line 29 of file pgrid.h.
Referenced by run(), runphysics(), t_grid::t_grid(), t_particles::t_particles(), t_pgrid(), and ~t_pgrid().
t_pgrid::_mouse t_pgrid::mouse
Referenced by t_workspace::dozoom(), t_workspace::mouse_button_event(), and run().
The documentation for this class was generated from the following files:
code/pgrid/src/pgrid.h
code/pgrid/src/pgrid.cpp