pgrid: t_tool_paintgrid_singlepixel Class Reference
t_tool_paintgrid_singlepixel Class Reference
#include <editortools.h>
Public Member Functions
t_tool_paintgrid_singlepixel (t_editor *e)
void phys_tick (float time)
void drawhint ()
Detailed Description
Definition at line 9 of file editortools.h.
Constructor & Destructor Documentation
t_tool_paintgrid_singlepixel::t_tool_paintgrid_singlepixel (t_editor * e) [inline]
Definition at line 14 of file editortools.h.
References t_editortool::mouse_buttons.
Member Function Documentation
void t_tool_paintgrid_singlepixel::phys_tick (float time) [inline, virtual]
Reimplemented from t_editortool.
Definition at line 19 of file editortools.h.
References t_image::current_layer(), t_pgrid::current_workspace(), t_pgrid::getinstance(), t_layer::grid, t_workspace::image, t_editortool::mouse_buttons, t_editortool::mouse_img_pos, t_grid::paint_pixel_additive(), t_editortool::phys_tick(), and vec::random_deviation().
void t_tool_paintgrid_singlepixel::drawhint () [inline]
Definition at line 36 of file editortools.h.
The documentation for this class was generated from the following file:
code/pgrid/src/editortools.h