pgrid: t_editor Class Reference
t_editor Class Reference
#include <editor.h>
Public Member Functions
bool dowrap ()
bool lerpmouse ()
bool showparticles ()
t_editor (t_pgrid *_pgrid)
~t_editor ()
t_brush * getbrush ()
void phys_tick (float time)
void keyboard_event (SDL_KeyboardEvent &evt)
void mouse_button_event (SDL_MouseButtonEvent &evt)
void mouse_motion_event (SDL_MouseMotionEvent &evt)
Public Attributes
class t_pgrid * pgrid
bool wrapmode
bool lerpmouse
bool showparticles
Private Attributes
struct {
bool wrapmode
bool lerpmouse
bool showparticles
} options
t_editortool * tools [2]
int selected_tool
t_brush * curbrush
Detailed Description
Definition at line 11 of file editor.h.
Constructor & Destructor Documentation
t_editor::t_editor (t_pgrid * _pgrid)
Definition at line 21 of file editor.cpp.
References options, selected_tool, and tools.
t_editor::~t_editor () [inline]
Definition at line 36 of file editor.h.
References curbrush, and tools.
Member Function Documentation
bool t_editor::dowrap () [inline]
Definition at line 30 of file editor.h.
References options.
Referenced by t_particles::add(), t_particles::clamp_particle(), t_grid::getpoint(), and t_grid::getpoint_editing().
bool t_editor::lerpmouse () [inline]
Definition at line 31 of file editor.h.
References options.
bool t_editor::showparticles () [inline]
Definition at line 32 of file editor.h.
References options.
t_brush* t_editor::getbrush () [inline]
Definition at line 43 of file editor.h.
References curbrush.
Referenced by t_tool_addparticles::erase(), keyboard_event(), t_tool_paintgrid_brush::mousepaint(), t_tool_push::mousepaint(), t_tool_addparticles::paint(), and t_tool_paintgrid_spraycan::phys_tick().
void t_editor::phys_tick (float time) [inline]
Definition at line 48 of file editor.h.
References t_editortool::phys_tick(), selected_tool, and tools.
Referenced by t_pgrid::runphysics().
void t_editor::keyboard_event (SDL_KeyboardEvent & evt) [inline, virtual]
Implements input_handler.
Definition at line 53 of file editor.h.
References getbrush(), t_brush::getheight(), t_brush::getwidth(), options, t_brush::resize(), selected_tool, and tools.
Referenced by t_pgrid::run().
void t_editor::mouse_button_event (SDL_MouseButtonEvent & evt) [inline, virtual]
Implements input_handler.
Definition at line 91 of file editor.h.
References t_editortool::mouse_button_event(), selected_tool, and tools.
Referenced by t_pgrid::run().
void t_editor::mouse_motion_event (SDL_MouseMotionEvent & evt) [inline, virtual]
Implements input_handler.
Definition at line 95 of file editor.h.
References t_editortool::mouse_motion_event(), selected_tool, and tools.
Referenced by t_pgrid::run().
Member Data Documentation
bool t_editor::wrapmode
Definition at line 16 of file editor.h.
bool t_editor::lerpmouse
Definition at line 17 of file editor.h.
Referenced by t_editortool::phys_tick().
bool t_editor::showparticles
Definition at line 18 of file editor.h.
Referenced by t_particles::render().
struct { ... } t_editor::options [private]
Referenced by dowrap(), keyboard_event(), lerpmouse(), showparticles(), and t_editor().
t_editortool* t_editor::tools[2] [private]
Definition at line 21 of file editor.h.
Referenced by keyboard_event(), mouse_button_event(), mouse_motion_event(), phys_tick(), t_editor(), and ~t_editor().
int t_editor::selected_tool [private]
Definition at line 22 of file editor.h.
Referenced by keyboard_event(), mouse_button_event(), mouse_motion_event(), phys_tick(), and t_editor().
t_brush* t_editor::curbrush [private]
Definition at line 24 of file editor.h.
Referenced by getbrush(), and ~t_editor().
class t_pgrid* t_editor::pgrid
Definition at line 28 of file editor.h.
The documentation for this class was generated from the following files:
code/pgrid/src/editor.h
code/pgrid/src/editor.cpp