pgrid: t_screen Struct Reference
t_screen Struct Reference
#include <screen.h>
Public Member Functions
t_screen ()
void registertexture (t_texture *t)
void unregistertexture (t_texture *t)
void rebuildtextures ()
void setortho ()
float getaspect ()
float getyfov ()
float calcplanedist ()
void setperspective (float fov=90, float asp=1.0)
void gl_init (int w, int h)
void init (int w, int h, bool fullscreen)
void togglefullscreen ()
Public Attributes
int width
int height
bool fullscreen
bool ortho
float fov
float aspmod
float planedist
SDL_Surface * sdl_surface
std::vector< class
t_texture * > textures
Detailed Description
Definition at line 6 of file screen.h.
Constructor & Destructor Documentation
t_screen::t_screen () [inline]
Definition at line 17 of file screen.h.
Member Function Documentation
void t_screen::registertexture (t_texture * t)
Definition at line 17 of file screen.cpp.
References textures.
Referenced by t_texture::t_texture().
void t_screen::unregistertexture (t_texture * t)
Definition at line 22 of file screen.cpp.
References textures.
Referenced by t_texture::~t_texture().
void t_screen::rebuildtextures ()
Definition at line 28 of file screen.cpp.
References textures.
Referenced by gl_init().
void t_screen::setortho ()
Definition at line 34 of file screen.cpp.
References height, ortho, and width.
Referenced by gl_init(), and t_workspace::keyboard_event().
float t_screen::getaspect () [inline]
Definition at line 27 of file screen.h.
References aspmod, height, and width.
Referenced by setperspective().
float t_screen::getyfov () [inline]
Definition at line 32 of file screen.h.
References aspmod, fov, height, and width.
Referenced by setperspective().
float t_screen::calcplanedist ()
Definition at line 75 of file screen.cpp.
References height, planedist, and width.
Referenced by setperspective().
void t_screen::setperspective (float fov = 90, float asp = 1.0)
Definition at line 42 of file screen.cpp.
References aspmod, calcplanedist(), getaspect(), getyfov(), height, ortho, planedist, and width.
Referenced by gl_init(), and t_workspace::keyboard_event().
void t_screen::gl_init (int w, int h)
Definition at line 60 of file screen.cpp.
References height, ortho, rebuildtextures(), setortho(), setperspective(), and width.
Referenced by init(), and t_pgrid::run().
void t_screen::init (int w, int h, bool fullscreen)
Definition at line 99 of file screen.cpp.
References fatal(), gl_init(), and sdl_surface.
Referenced by t_pgrid::t_pgrid(), and togglefullscreen().
void t_screen::togglefullscreen ()
Definition at line 113 of file screen.cpp.
References fullscreen, height, init(), and width.
Referenced by t_workspace::keyboard_event().
Member Data Documentation
int t_screen::width
Definition at line 8 of file screen.h.
Referenced by calcplanedist(), t_workspace::centerimage(), t_workspace::dozoom(), getaspect(), getyfov(), gl_init(), t_workspace::render(), t_workspace::renderbg(), t_workspace::setcenter(), setortho(), setperspective(), and togglefullscreen().
int t_screen::height
Definition at line 8 of file screen.h.
Referenced by calcplanedist(), t_workspace::centerimage(), t_workspace::dozoom(), getaspect(), getyfov(), gl_init(), t_workspace::render(), t_workspace::renderbg(), t_workspace::setcenter(), setortho(), setperspective(), and togglefullscreen().
bool t_screen::fullscreen
Definition at line 9 of file screen.h.
Referenced by togglefullscreen().
bool t_screen::ortho
Definition at line 10 of file screen.h.
Referenced by gl_init(), t_workspace::keyboard_event(), t_workspace::render(), setortho(), and setperspective().
float t_screen::fov
Definition at line 11 of file screen.h.
Referenced by getyfov().
float t_screen::aspmod
Definition at line 11 of file screen.h.
Referenced by getaspect(), getyfov(), and setperspective().
float t_screen::planedist
Definition at line 12 of file screen.h.
Referenced by calcplanedist(), t_workspace::render(), and setperspective().
SDL_Surface* t_screen::sdl_surface
Definition at line 14 of file screen.h.
Referenced by init(), and t_pgrid::run().
std::vector<class t_texture *> t_screen::textures
Definition at line 15 of file screen.h.
Referenced by rebuildtextures(), registertexture(), and unregistertexture().
The documentation for this struct was generated from the following files:
code/pgrid/src/screen.h
code/pgrid/src/screen.cpp