pgrid: t_particles::t_quadarray Struct Reference
t_particles::t_quadarray
t_particles::t_quadarray Struct Reference
Public Member Functions
t_quadarray ()
~t_quadarray ()
void reset (int maxsize)
void alloc (int maxsize)
void addquad (float x, float y, float z, float size)
void updatequad (int idx, float x, float y, float z, float size)
void draw ()
Public Attributes
vec * texcoords
vert3 * verts
int nquads
int arraysize
Detailed Description
Definition at line 31 of file particles.h.
Constructor & Destructor Documentation
t_particles::t_quadarray::t_quadarray () [inline]
Definition at line 38 of file particles.h.
t_particles::t_quadarray::~t_quadarray () [inline]
Definition at line 39 of file particles.h.
References texcoords, and verts.
Member Function Documentation
void t_particles::t_quadarray::reset (int maxsize)
Definition at line 207 of file particles.cpp.
References alloc(), and nquads.
void t_particles::t_quadarray::alloc (int maxsize)
Definition at line 213 of file particles.cpp.
References arraysize, texcoords, and verts.
Referenced by t_particles::complexphysics(), reset(), and t_particles::updatearrays().
void t_particles::t_quadarray::addquad (float x, float y, float z, float size)
Definition at line 239 of file particles.cpp.
References nquads, and updatequad().
void t_particles::t_quadarray::updatequad (int idx, float x, float y, float z, float size)
Definition at line 223 of file particles.cpp.
References texcoords, verts, vert3::x, vec::x, vert3::y, vec::y, and vert3::z.
Referenced by addquad(), and t_particles::updatearrays().
void t_particles::t_quadarray::draw ()
Definition at line 245 of file particles.cpp.
References nquads, texcoords, and verts.
Referenced by t_particles::renderarrays().
Member Data Documentation
vec* t_particles::t_quadarray::texcoords
Definition at line 33 of file particles.h.
Referenced by alloc(), draw(), updatequad(), and ~t_quadarray().
vert3* t_particles::t_quadarray::verts
Definition at line 34 of file particles.h.
Referenced by alloc(), draw(), updatequad(), and ~t_quadarray().
int t_particles::t_quadarray::nquads
Definition at line 35 of file particles.h.
Referenced by addquad(), draw(), reset(), and t_particles::updatearrays().
int t_particles::t_quadarray::arraysize
Definition at line 36 of file particles.h.
Referenced by alloc().
The documentation for this struct was generated from the following files:
code/pgrid/src/particles.h
code/pgrid/src/particles.cpp