pgrid: vector< T > Struct Template Reference
vector< T > Struct Template Reference
#include <main.h>
Public Member Functions
vector ()
~vector ()
vector (vector< T > &v)
void operator= (vector< T > &v)
T & add (const T &x)
T & add ()
T & pop ()
T & last ()
void drop ()
bool empty () const
int length () const
int size () const
T & operator[] (int i)
const T & operator[] (int i) const
void setsize (int i)
void setsize_fast (int i)
void deletecontentsp ()
void deletecontentsa ()
T * getbuf ()
void sort (void *cf)
void * _realloc (void *p, int oldsize, int newsize)
void vrealloc ()
T remove (int i)
void removeobj (T &o)
T & insert (int i, const T &e)
Public Attributes
T * buf
int alen
int ulen
Detailed Description
template<class T>
struct vector< T >
Definition at line 155 of file main.h.
Constructor & Destructor Documentation
template<class T> vector< T >::vector () [inline]
Definition at line 161 of file main.h.
template<class T> vector< T >::~vector () [inline]
Definition at line 168 of file main.h.
template<class T> vector< T >::vector (vector< T > & v)
Member Function Documentation
template<class T> void vector< T >::operator= (vector< T > & v)
template<class T> T& vector< T >::add (const T & x) [inline]
Definition at line 173 of file main.h.
References vec::x.
Referenced by t_particles::add(), and t_particles::keyboard_event().
template<class T> T& vector< T >::add () [inline]
Definition at line 180 of file main.h.
template<class T> T& vector< T >::pop () [inline]
Definition at line 187 of file main.h.
template<class T> T& vector< T >::last () [inline]
Definition at line 188 of file main.h.
template<class T> void vector< T >::drop () [inline]
Definition at line 189 of file main.h.
template<class T> bool vector< T >::empty () const [inline]
Definition at line 190 of file main.h.
template<class T> int vector< T >::length () const [inline]
Definition at line 192 of file main.h.
template<class T> int vector< T >::size () const [inline]
Definition at line 193 of file main.h.
Referenced by t_particles::complexphysics(), t_particles::renderquads(), and t_particles::updatearrays().
template<class T> T& vector< T >::operator[] (int i) [inline]
Definition at line 194 of file main.h.
References ASSERT.
template<class T> const T& vector< T >::operator[] (int i) const [inline]
Definition at line 195 of file main.h.
References ASSERT.
template<class T> void vector< T >::setsize (int i) [inline]
Definition at line 196 of file main.h.
References ASSERT.
template<class T> void vector< T >::setsize_fast (int i) [inline]
Definition at line 197 of file main.h.
References ASSERT.
Referenced by t_particles::keyboard_event().
template<class T> void vector< T >::deletecontentsp () [inline]
Definition at line 199 of file main.h.
template<class T> void vector< T >::deletecontentsa () [inline]
Definition at line 200 of file main.h.
template<class T> T* vector< T >::getbuf () [inline]
Definition at line 202 of file main.h.
template<class T> void vector< T >::sort (void * cf) [inline]
Definition at line 204 of file main.h.
template<class T> void* vector< T >::_realloc (void * p, int oldsize, int newsize) [inline]
Definition at line 206 of file main.h.
template<class T> void vector< T >::vrealloc () [inline]
Definition at line 215 of file main.h.
template<class T> T vector< T >::remove (int i) [inline]
Definition at line 221 of file main.h.
template<class T> void vector< T >::removeobj (T & o) [inline]
Definition at line 229 of file main.h.
template<class T> T& vector< T >::insert (int i, const T & e) [inline]
Definition at line 234 of file main.h.
Member Data Documentation
template<class T> T* vector< T >::buf
Definition at line 157 of file main.h.
template<class T> int vector< T >::alen
Definition at line 158 of file main.h.
template<class T> int vector< T >::ulen
Definition at line 159 of file main.h.
The documentation for this struct was generated from the following file:
code/pgrid/src/main.h