pgrid: t_texture Struct Reference
t_texture Struct Reference
#include <texture.h>
Public Member Functions
void bind ()
void upload ()
void rebuild ()
void setpixels (int w, int h, int b, void *pixels)
t_texture (int w, int h, int b, void *pixels=0, bool _mipmapped=false)
~t_texture ()
Public Attributes
GLuint glname
int width
int height
int bpp
bool mipmapped
u8 * pixelcache
Detailed Description
Definition at line 4 of file texture.h.
Constructor & Destructor Documentation
t_texture::t_texture (int w, int h, int b, void * pixels = 0, bool _mipmapped = false)
Definition at line 22 of file texture.cpp.
References bind(), t_pgrid::getinstance(), glname, mipmapped, pixelcache, t_screen::registertexture(), t_pgrid::screen, and setpixels().
t_texture::~t_texture ()
Definition at line 33 of file texture.cpp.
References t_pgrid::getinstance(), glname, pixelcache, t_pgrid::screen, and t_screen::unregistertexture().
Member Function Documentation
void t_texture::bind () [inline]
Definition at line 12 of file texture.h.
References glname.
Referenced by t_particles::render(), t_workspace::renderbg(), t_texture(), and upload().
void t_texture::upload () [inline]
Definition at line 17 of file texture.h.
References bind(), bpp, height, mipmapped, pixelcache, and width.
Referenced by rebuild(), and setpixels().
void t_texture::rebuild () [inline]
Definition at line 35 of file texture.h.
References glname, and upload().
void t_texture::setpixels (int w, int h, int b, void * pixels) [inline]
Definition at line 42 of file texture.h.
References bpp, height, pixelcache, upload(), and width.
Referenced by t_texture().
Member Data Documentation
GLuint t_texture::glname
Definition at line 6 of file texture.h.
Referenced by bind(), rebuild(), t_texture(), and ~t_texture().
int t_texture::width
Definition at line 7 of file texture.h.
Referenced by t_workspace::renderbg(), setpixels(), and upload().
int t_texture::height
Definition at line 7 of file texture.h.
Referenced by t_workspace::renderbg(), setpixels(), and upload().
int t_texture::bpp
Definition at line 8 of file texture.h.
Referenced by setpixels(), and upload().
bool t_texture::mipmapped
Definition at line 9 of file texture.h.
Referenced by t_texture(), and upload().
u8* t_texture::pixelcache
Definition at line 10 of file texture.h.
Referenced by setpixels(), t_texture(), upload(), and ~t_texture().
The documentation for this struct was generated from the following files:
code/pgrid/src/texture.h
code/pgrid/src/texture.cpp